- public/jobs.html
Closes #27 
**Enhancements to `jobs listing Page`:**
Implemented dynamic search functionality to filter jobs by Job Title, Type, and Location in real-time. Clearing search inputs restores all job listings.
Here are the video:
https://github.com/user-attachments/assets/338e5bef-c52b-4164-9aad-88de6fddafa5
> Feat. Fix #27 Added Search functionality

- public/contactUs.html
- public/index.html
fixes:  #4 
On click on contact us
https://github.com/user-attachments/assets/0caa523e-b34a-4b00-912d-61d3b3871692
please review and add label
> Add contact us page

- public/index.css
- Added a hover effect to the FAQ question buttons to automatically display the respective answers when hovered.
- Updated the `.faq-answer` to show when the corresponding `.faq-question` button is hovered using the `:hover` pseudo-class and adjacent sibling selector.
- Added smooth transitions and background color change on hover to improve user experience.
- Modified CSS to add hover-based display of answers.
- Updated styles for `.faq-question` and `.faq-answer` for better interactivity and visibility.
fixes: #26
> Implemented Hover Effect to Automatically Display FAQ Answers

- public/index.html
- public/internships.html
- public/jobs.html
- public/mentorship.html
I've added home button to all pages
> Home button added

- public/internships.css
- public/internships.html
Styled the cards on the internship page
#1
> #1 card styled

- public/index.html
- public/internships.css
- public/internships.html
- public/jobs.html
- public/mentorship.html
- public/resources.html
- public/script.js
**Linked Issue:**  
Fixes #55 
**Description:**  
This PR addresses **Issue #55** by suggesting the integration of a **chatbot** into the **Lumina** project to enhance user interaction, provide instant support, and improve the overall usability of the platform. The chatbot aims to guide users through features, troubleshoot issues in real time, and ensure seamless navigation across the platform.  
**Benefits of the Feature:**  
- **User Engagement:**  
- The chatbot will assist users in exploring **Lumina’s** features, boosting overall engagement and retention.  
- **Efficient Support:**  
- Provides instant answers to common queries, minimizing frustration and enhancing user satisfaction.  
- **Accessibility:**  
- Simplifies the onboarding process by guiding new users through the …
> Add Chatbot Integration to Enhance User Engagement and Support  

- public/validation.js
It enhances the signup form by adding validation for the 'firstname' field, ensuring it accepts only letters, spaces, and hyphens. Provides clear error message for better user experience.
Fixes #23
> Add name validation for signup form

- public/index.html
Fixes: #35 
@Abhay-hack Please review
I have resolved the conflicts
> social media icons added

- public/events&webinar.css
- public/events&webinar.html
- public/index.css
- public/internships.css
- public/internships.html
- public/jobs.css
- public/jobs.html
- public/mentorship.css
- public/mentorship.html
- public/resources.css
- public/resources.html
I have made changes such that each page has same navbar with same font styles.
> fixed navbars for all pages

- public/index.css
Closes #99 - fixed homemain heading overflow using flex wrap
> fixed homemain heading overflow using flex wrap - Closes #99

- public/error.css
- public/error.html
##error #65
1. custom error page with styling for 404 errors
2. add emoji to see more attractive
> Add custom error page with styling for 404 errors

- public/index.css
- public/index.html
- public/testimonial.css
fixes #106 I resolved the issue
pls add suitable labels and merge
@Mayureshd-18 @Abhay-hack
> Fixed  Restructing the Landing Page UI and CSS

- public/contact.css
- public/contact.html
- public/contact.js
- public/index.html
Fixes #76 
I have added a  "Contact Us" page to the project. The page includes a responsive form styled with CSS and features a mock reCAPTCHA checkbox for a basic "I'm not a robot" verification mechanism. The form collects user details like name, email, and message. The features added are described below:
1. Contact Us Form:
Fields: Name, Email, Message (all required).
Mock reCAPTCHA: A simple checkbox labeled "I'm not a robot" (no backend validation).
2. UI Enhancements:
Styled with a light yellow background for an appealing look.
Responsive design to ensure usability across devices.
3. Functionality:
Successful submission message once the form is filled and submitted.
Clean and accessible HTML structure.
The mock reCAPTCHA serves as a placeholder for actual spam prevention. No …
> Fixes #76 Added a contact us page 

- public/resources.html
Closes #136 
Added code360 to PRACTISE and added a redirection link to the platform.
@Abhay-hack please review the PR and assign points
> Added code360 to PRACTISE

- public/contributors/contributor.css
- public/contributors/contributor.html
- public/contributors/contributor.js
- public/index.html
#92 solved contributor page added to website that auto fetch contributors that are currently contributing to your project
https://github.com/user-attachments/assets/92038eeb-978e-4fba-8a06-c3d356fe9076
> contributors page added to website

- public/resources.css
- public/resources.html
Fixes #131 
I have done the necessary changes to add the footer section to the resources page
> footer section added to the resources page

- public/PostIntern.css
- public/PostIntern.html
> navbar added to post an internship page

- public/internships.css
- public/internships.html
I have changed ui of internship cards so that all look similar and clean.
closes #125
> Changed ui of internship cards

- package-lock.json
- public/index.css
Fix #141 
I have made the FAQ section responsive by introducing media queries to the design.
@Abhay-hack @Aarzookhunger  please review and merge my pr.
> Responsive FAQ section 

- public/AddEvent.html
- public/Apply.html
> navbar added to mentorship and event/webinar page

- public/AllmediaLts.html
- public/ITWorlds.html
- public/ITinfosy.html
- public/InfoStatics.html
- public/contactUs.html
- public/copyrightYear.js
- public/index.html
- public/internships.html
- public/jobs.html
- public/massIdea.html
- public/mentorship.html
- public/resources.html
- public/softwareSolution.html
> Issue No. #175 [BUG FIXED] In the footer section, the copyright year should be dynamically generated instead of being statically hardcoded. 

- public/events&webinar.css
- public/events&webinar.html
#171 solved 
https://github.com/user-attachments/assets/af7f2a4d-cae3-4fe9-938a-5df2e51c7d1b
>  footer added to event webinar page

- public/index.css
- public/index.html
- public/scrollTop.js
> Issue No. #88 [FIXED] Scroll To Top Button Added.

- public/AllmediaLts.html
- public/ITWorlds.html
- public/ITinfosy.html
- public/InfoStatics.html
- public/index.html
- public/internships.html
- public/jobs.css
- public/massIdea.html
- public/softwareSolution.html
Solved https://github.com/Abhay-hack/Lumina/issues/165
**Summary of Changes:**
1. Linked the "Apply Now" page with all sections of "View Details" in:
- Job Section
- Internship Section
2. Fixed an issue in the Internship Section where "Post an Internship" was repeated twice. Removed the duplicate.
**Impact of Changes:**
- Improved website navigation and user experience by providing direct access to the "Apply Now" page from relevant sections.
- Resolved duplication issue in the Internship Section, making the content more concise and professional.
**Request:**
Please review these changes and merge this pull request. Let me know if you have any further suggestions or require additional updates to enhance the website further.
Thank you for your time and support!
Before...
After
> Apply Page link

- public/index.html
> fixed double change issue

- public/PostIntern.css
- public/PostIntern.html
> footer added to post and internship  form page
